language: node_js
sudo: false
node_js:
  - "iojs"
  - "0.12"
  - "4"
  - "5"
services:
  - mysql
before_script:
  - mysql -e "create database IF NOT EXISTS dbmigrate;" -uroot
  - mysql -Ddbmigrate -uroot < test/fixtures/travis.sql
script:
  - npm test
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/codecov
